# Generated by Django 6.0.5 on 2026-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
