# Generated by Django 6.0.5 on 2026-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='transferred_to_shelter',
            field=models.BooleanField(default=False),
        ),
    ]
