# Generated by Django 6.0.5 on 2026-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_transferred_to_shelter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='transferred_to_shelter',
            new_name='is_adopted',
        ),
        migrations.AddField(
            model_name='cat',
            name='particularity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cat',
            name='provenance',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
