services:
  web:
    build: .
    container_name: django_rest_api
    command: /entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - shelter_db

  db:
    image: postgres:16
    container_name: django_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${CAT_POSTGRES_DB}
      POSTGRES_USER: ${CAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CAT_POSTGRES_PASSWORD}
    ports:
      - "5434:5432"

  shelter_db:
    image: postgres:16
    container_name: django_shelter_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${SHELTER_POSTGRES_DB}
      POSTGRES_USER: ${SHELTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SHELTER_POSTGRES_PASSWORD}
    ports:
      - "5435:5432"