# Generated by Django 6.0.5 on 2026-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheltercat',
            old_name='arrival_date',
            new_name='adoption_date',
        ),
        migrations.AddField(
            model_name='sheltercat',
            name='particularity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sheltercat',
            name='provenance',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sheltercat',
            name='boarding_status',
            field=models.CharField(default='adopted', max_length=50),
        ),
    ]
